version: "3.8"

services:
  backend:
    container_name: chart_backend
    build:
      context: ./backend
      args:
        NODE_ENV: development
    init: true
    command: bash -c "wait-for-it -s -t 360 postgres:5432 -- npm run start:dev"
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/prisma:/home/node/app/prisma
    depends_on:
      - postgres

  frontend:
    container_name: chart_frontend
    command: npm run dev
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    init: true
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./frontend/src:/home/node/app/src
      - ./frontend/public:/home/node/app/public
    depends_on:
      - postgres
      - backend

  postgres:
    image: postgres:16
    init: true
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data/pgdata
    command:
      - "postgres"